baseURL = 'https://alexisjanvier.net/'
languageCode = 'fr'
defaultContentLanguage = 'fr'
title = 'Alexis Janvier'
theme = 'alexisjanvier'
[params]
  description = 'Internet is not dead. It just smells funny.'
  homeMetaContent = 'Internet is not dead. It just smells funny.'
[taxonomies]
  category = 'categories'
  series = 'series'
  tag = 'tags'
[related]
  includeNewer = true
  threshold = 100
  toLower = false
[[related.indices]]
  name = 'tags'
  weight = 100
[[related.indices]]
  name = 'keywords'
  weight = 60
[imaging]
# Default resample filter used for resizing. Default is Box,
# a simple and fast averaging filter appropriate for downscaling.
# See https://github.com/disintegration/imaging
resampleFilter = "Box"
# Default JPEG or WebP quality setting. Default is 75.
quality = 80
# Default hint about what type of image. Currently only used for WebP encoding.
# Default is "photo".
# Valid values are "picture", "photo", "drawing", "icon", or "text".
hint = "photo"
anchor = "smart"
[menu]
[[menu.nav]]
  name = 'Accueil'
  url = '/'
  weight = 1
[[menu.nav]]
  name = 'Blog'
  url = '/blog'
  weight = 2
[[menu.nav]]
  name = 'Talks'
  url = '/talks'
  weight = 3
[[menu.nav]]
  name = 'À propos'
  url = '/a-propos'
  weight = 4
copyright = 'This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License.'
rssLimit = 2
[author]
  name = 'Alexis Janvier'
[sitemap]
  changefreq = 'weekly'
  filename = 'sitemap.xml'
  priority = 0.5
