baseURL = 'https://alexisjanvier.net/'
languageCode = 'fr'
defaultContentLanguage = 'fr'
title = 'Alexis Janvier'
theme = 'alexisjanvier'
[params]
  description = 'Internet is not dead. It just smells funny.'
  homeMetaContent = 'Internet is not dead. It just smells funny.'
[taxonomies]
  category = 'categories'
  series = 'series'
  tag = 'tags'
[related]
  includeNewer = true
  threshold = 100
  toLower = false
[[related.indices]]
  name = 'tags'
  weight = 100
[[related.indices]]
  name = 'keywords'
  weight = 60
